### PR TITLE
Added test and code updates

### PR DESCRIPTION
**Pull request by korsbacken**
Added if (driver =! null) check on all driver.quit() thoughout the project

Removed "page title" scenario in checkoutPage feature file since it was just a test (I think).

Removed "Background" scenario in checkoutPage feature file for troubleshooting. Don't think we used that in our actual tests.

Added ChromeOptions in Before method in checkoutPageStepDef file to set incognito and maximize window.

Added one test.

I also made some changes (commented out some code to troubleshoot) to your code @dkakandki in ShopPageStepDefs but I guess it doesn't matter since you created a new file.

### CODE REVIEW

**Comment by korsbacken** [comment]
I also made some changes (commented out some code to troubleshoot) to your code @dkakandki in ShopPageStepDefs but I guess it doesn't matter since you created a new file.

**Review by mhuggare — CHANGES_REQUESTED** [review]
hej,
think all is good, except you removed a line for my waiting.
in the CheckoutPageStepDefs on row 29 i had this line
wait = new WebDriverWait(driver, Duration.ofSeconds(1)); // Ange väntetiden här
maybe don't need to be in a before, but want the line somewhere

(had to have a wait to get stuff put in cart properly)

**Comment by korsbacken** [comment]
Sorry about that 😅 Did a lot of troubleshooting by removing and adding code. Forgot to add it back in.

Edit: Actually it's still there on my branch.
image

**Comment by mhuggare** [comment]
strange. i will approve and if the line has dissapeared it's easy to put it back somewhere

**Review by mhuggare — APPROVED** [review]

**Pull request merged**
