### PR TITLE
updated branches in maven.yml to check if it works

### PR DESCRIPTION
**Pull request by dkakandki**

### CODE REVIEW

**Comment by korsbacken** [comment]
Was the branch name changed from "main" to "master" automatically when you updated the maven.yml file? Or did you change that as well?
How do I change the branch name locally? 😅

**Comment by dkakandki** [comment]
I changed the branch name, in order to keep it same as other repo. I think pull from remote might work. not sure.

**Comment by korsbacken** [comment]
Let's try it! 👍

**Review by korsbacken — APPROVED** [review]
Approved.

**Comment by dkakandki** [comment]
I have found the solution for changing branch in  the local you can checks your teams.

**Pull request merged**
